version: '3'
services:
  container1:
    build: .
    ports:
      - "5001:5000"
    environment:
      - NAME=World
  container2:
    build: .
    ports:
      - "5002:5000"
    environment:
      - NAME=World